import { DailyReport, Trend, BreakoutSingle, ScrapedContent, Platform } from "./types";

const today = new Date().toISOString().split("T")[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0];
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString().split("T")[0];

function makeContent(overrides: Partial<ScrapedContent> & { id: string }): ScrapedContent {
  return {
    creator_id: "c1",
    creator_name: "Alex Hormozi",
    creator_avatar: "",
    platform: "youtube",
    post_url: "https://youtube.com/watch?v=example",
    thumbnail_url: "",
    caption_text: "",
    hook_text: "",
    view_count: 100000,
    likes: 5000,
    comments: 300,
    shares: 200,
    published_at: new Date().toISOString(),
    scraped_at: new Date().toISOString(),
    views_per_hour: 8333,
    breakout_score: 7.5,
    content_format: "talking_head",
    ...overrides,
  };
}

const trend1Sources: ScrapedContent[] = [
  makeContent({
    id: "sc1",
    creator_name: "Alex Hormozi",
    platform: "youtube",
    post_url: "https://youtube.com/watch?v=build1",
    view_count: 342000,
    likes: 18200,
    comments: 1340,
    shares: 890,
    hook_text: "I filmed every minute of building my app for 30 days",
    breakout_score: 9.2,
    content_format: "talking_head",
  }),
  makeContent({
    id: "sc2",
    creator_name: "Codie Sanchez",
    creator_id: "c2",
    platform: "tiktok",
    post_url: "https://tiktok.com/@codiesanchez/video/build2",
    view_count: 287000,
    likes: 24100,
    comments: 2100,
    shares: 1560,
    hook_text: "Nobody talks about the ugly middle of building",
    breakout_score: 8.7,
    content_format: "broll",
  }),
  makeContent({
    id: "sc3",
    creator_name: "Gary Vee",
    creator_id: "c3",
    platform: "instagram",
    post_url: "https://instagram.com/p/build3",
    view_count: 198000,
    likes: 15800,
    comments: 980,
    shares: 720,
    hook_text: "Day 1 vs Day 30 of building in public",
    breakout_score: 7.9,
    content_format: "text_overlay",
  }),
];

const trend2Sources: ScrapedContent[] = [
  makeContent({
    id: "sc4",
    creator_name: "Sahil Bloom",
    creator_id: "c4",
    platform: "youtube",
    post_url: "https://youtube.com/watch?v=hook1",
    view_count: 256000,
    likes: 12400,
    comments: 890,
    shares: 670,
    hook_text: "Stop posting content. Start posting contrarian takes.",
    breakout_score: 8.4,
    content_format: "talking_head",
  }),
  makeContent({
    id: "sc5",
    creator_name: "Dan Koe",
    creator_id: "c5",
    platform: "tiktok",
    post_url: "https://tiktok.com/@dankoe/video/hook2",
    view_count: 189000,
    likes: 16700,
    comments: 1420,
    shares: 980,
    hook_text: "Everyone is wrong about content strategy in 2026",
    breakout_score: 7.8,
    content_format: "talking_head",
  }),
];

const trend3Sources: ScrapedContent[] = [
  makeContent({
    id: "sc6",
    creator_name: "Ali Abdaal",
    creator_id: "c6",
    platform: "youtube",
    post_url: "https://youtube.com/watch?v=screen1",
    view_count: 412000,
    likes: 22100,
    comments: 1890,
    shares: 1240,
    hook_text: "I replaced my entire content workflow with AI — here's what happened",
    breakout_score: 9.5,
    content_format: "screen_recording",
  }),
  makeContent({
    id: "sc7",
    creator_name: "Justin Welsh",
    creator_id: "c7",
    platform: "instagram",
    post_url: "https://instagram.com/p/screen2",
    view_count: 167000,
    likes: 11200,
    comments: 890,
    shares: 560,
    hook_text: "My AI content system that creates 30 days of posts in 2 hours",
    breakout_score: 8.1,
    content_format: "screen_recording",
  }),
  makeContent({
    id: "sc8",
    creator_name: "Iman Gadzhi",
    creator_id: "c8",
    platform: "tiktok",
    post_url: "https://tiktok.com/@imangadzhi/video/screen3",
    view_count: 298000,
    likes: 19800,
    comments: 2340,
    shares: 1780,
    hook_text: "This AI tool writes better hooks than 99% of creators",
    breakout_score: 8.8,
    content_format: "screen_recording",
  }),
];

const trend4Sources: ScrapedContent[] = [
  makeContent({
    id: "sc9",
    creator_name: "Hormozi",
    creator_id: "c1",
    platform: "youtube",
    post_url: "https://youtube.com/watch?v=thread1",
    view_count: 178000,
    likes: 9800,
    comments: 670,
    shares: 450,
    hook_text: "I turned a Twitter thread into a $50k product launch",
    breakout_score: 7.6,
    content_format: "talking_head",
  }),
  makeContent({
    id: "sc10",
    creator_name: "Nicolas Cole",
    creator_id: "c9",
    platform: "instagram",
    post_url: "https://instagram.com/p/thread2",
    view_count: 145000,
    likes: 8900,
    comments: 560,
    shares: 390,
    hook_text: "Thread-to-video is the most underrated content strategy",
    breakout_score: 7.2,
    content_format: "text_overlay",
  }),
];

const trends: Trend[] = [
  {
    id: "t1",
    daily_report_id: "dr1",
    trend_name: 'The "Build in Public" Documentary Style',
    trend_summary:
      "Creators are filming raw, unedited footage of their daily building process and framing it as mini-documentaries. Velocity spiked 4.2x across 3 platforms in the last 8 hours. The format rewards authenticity over polish.",
    stage: "emerging",
    platform_signal_count: 3,
    platforms_detected_on: ["tiktok", "instagram", "youtube"],
    breakout_score_avg: 8.6,
    display_order: 1,
    first_detected_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    hooks: [
      { id: "h1", trend_id: "t1", hook_text: "I filmed every minute of building my app for 30 days", source_content_id: "sc1", rank: 1 },
      { id: "h2", trend_id: "t1", hook_text: "Nobody talks about the ugly middle of building", source_content_id: "sc2", rank: 2 },
      { id: "h3", trend_id: "t1", hook_text: "Day 1 vs Day 30 of building in public", source_content_id: "sc3", rank: 3 },
      { id: "h4", trend_id: "t1", hook_text: "Raw footage, no script, just building", source_content_id: "sc1", rank: 4 },
      { id: "h5", trend_id: "t1", hook_text: "What building a product actually looks like", source_content_id: "sc2", rank: 5 },
    ],
    source_videos: trend1Sources.map((c, i) => ({ id: `sv${i + 1}`, trend_id: "t1", content: c, display_order: i + 1 })),
  },
  {
    id: "t2",
    daily_report_id: "dr1",
    trend_name: "Contrarian Hot Takes Format",
    trend_summary:
      'Creators are opening with deliberately contrarian statements to drive engagement. The "everyone is wrong about X" hook pattern is generating 3.8x normal engagement rates. Comment sections are exploding with debate.',
    stage: "peaking",
    platform_signal_count: 2,
    platforms_detected_on: ["youtube", "tiktok"],
    breakout_score_avg: 8.1,
    display_order: 2,
    first_detected_at: new Date(Date.now() - 36 * 3600000).toISOString(),
    hooks: [
      { id: "h6", trend_id: "t2", hook_text: "Stop posting content. Start posting contrarian takes.", source_content_id: "sc4", rank: 1 },
      { id: "h7", trend_id: "t2", hook_text: "Everyone is wrong about content strategy in 2026", source_content_id: "sc5", rank: 2 },
      { id: "h8", trend_id: "t2", hook_text: "Unpopular opinion: consistency is overrated", source_content_id: "sc4", rank: 3 },
      { id: "h9", trend_id: "t2", hook_text: "The advice you're following is 5 years outdated", source_content_id: "sc5", rank: 4 },
      { id: "h10", trend_id: "t2", hook_text: "I stopped doing what every guru says and my views 10x'd", source_content_id: "sc4", rank: 5 },
    ],
    source_videos: trend2Sources.map((c, i) => ({ id: `sv${i + 4}`, trend_id: "t2", content: c, display_order: i + 1 })),
  },
  {
    id: "t3",
    daily_report_id: "dr1",
    trend_name: "AI Workflow Screen Recordings",
    trend_summary:
      "Screen recording walkthroughs of AI-powered content workflows are dominating. Creators showing their exact AI setup are seeing 5.1x velocity spikes. This is the strongest signal of the day across all 3 platforms.",
    stage: "emerging",
    platform_signal_count: 3,
    platforms_detected_on: ["youtube", "instagram", "tiktok"],
    breakout_score_avg: 8.8,
    display_order: 3,
    first_detected_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    hooks: [
      { id: "h11", trend_id: "t3", hook_text: "I replaced my entire content workflow with AI — here's what happened", source_content_id: "sc6", rank: 1 },
      { id: "h12", trend_id: "t3", hook_text: "My AI content system that creates 30 days of posts in 2 hours", source_content_id: "sc7", rank: 2 },
      { id: "h13", trend_id: "t3", hook_text: "This AI tool writes better hooks than 99% of creators", source_content_id: "sc8", rank: 3 },
      { id: "h14", trend_id: "t3", hook_text: "Watch me create a week of content in 20 minutes with AI", source_content_id: "sc6", rank: 4 },
      { id: "h15", trend_id: "t3", hook_text: "The exact AI stack I use to grow 10k followers/month", source_content_id: "sc7", rank: 5 },
    ],
    source_videos: trend3Sources.map((c, i) => ({ id: `sv${i + 6}`, trend_id: "t3", content: c, display_order: i + 1 })),
  },
  {
    id: "t4",
    daily_report_id: "dr1",
    trend_name: "Thread-to-Video Repurposing",
    trend_summary:
      "Converting high-performing Twitter threads into short-form video is gaining traction. Creators are overlaying thread text on b-roll or talking head footage. Engagement rate is 2.4x higher than original format posts.",
    stage: "peaking",
    platform_signal_count: 2,
    platforms_detected_on: ["youtube", "instagram"],
    breakout_score_avg: 7.4,
    display_order: 4,
    first_detected_at: new Date(Date.now() - 30 * 3600000).toISOString(),
    hooks: [
      { id: "h16", trend_id: "t4", hook_text: "I turned a Twitter thread into a $50k product launch", source_content_id: "sc9", rank: 1 },
      { id: "h17", trend_id: "t4", hook_text: "Thread-to-video is the most underrated content strategy", source_content_id: "sc10", rank: 2 },
      { id: "h18", trend_id: "t4", hook_text: "Take your best thread. Film yourself reading it. Post it as a Reel.", source_content_id: "sc9", rank: 3 },
      { id: "h19", trend_id: "t4", hook_text: "Why your threads deserve a second life as video", source_content_id: "sc10", rank: 4 },
      { id: "h20", trend_id: "t4", hook_text: "This one tweet became my highest-performing video ever", source_content_id: "sc9", rank: 5 },
    ],
    source_videos: trend4Sources.map((c, i) => ({ id: `sv${i + 9}`, trend_id: "t4", content: c, display_order: i + 1 })),
  },
];

const breakoutSingles: BreakoutSingle[] = [
  {
    id: "bs1",
    daily_report_id: "dr1",
    content: makeContent({
      id: "sc11",
      creator_name: "Mr Beast",
      creator_id: "c10",
      platform: "youtube",
      post_url: "https://youtube.com/watch?v=single1",
      view_count: 890000,
      likes: 45000,
      comments: 3200,
      shares: 2100,
      hook_text: "I gave away my entire business playbook for free",
      caption_text: "Everything I learned building a billion dollar brand — no gatekeeping",
      breakout_score: 9.1,
      content_format: "talking_head",
    }),
    display_order: 1,
  },
  {
    id: "bs2",
    daily_report_id: "dr1",
    content: makeContent({
      id: "sc12",
      creator_name: "Leila Hormozi",
      creator_id: "c11",
      platform: "instagram",
      post_url: "https://instagram.com/p/single2",
      view_count: 234000,
      likes: 18900,
      comments: 1100,
      shares: 780,
      hook_text: "The hiring mistake that cost me $2M",
      caption_text: "Learn from my expensive lesson in scaling too fast",
      breakout_score: 8.3,
      content_format: "talking_head",
    }),
    display_order: 2,
  },
  {
    id: "bs3",
    daily_report_id: "dr1",
    content: makeContent({
      id: "sc13",
      creator_name: "Naval",
      creator_id: "c12",
      platform: "tiktok",
      post_url: "https://tiktok.com/@naval/video/single3",
      view_count: 567000,
      likes: 34200,
      comments: 2800,
      shares: 4500,
      hook_text: "Wealth is created by doing what nobody else can do",
      caption_text: "The leverage equation nobody teaches you",
      breakout_score: 8.7,
      content_format: "text_overlay",
    }),
    display_order: 3,
  },
  {
    id: "bs4",
    daily_report_id: "dr1",
    content: makeContent({
      id: "sc14",
      creator_name: "Chris Do",
      creator_id: "c13",
      platform: "youtube",
      post_url: "https://youtube.com/watch?v=single4",
      view_count: 178000,
      likes: 9800,
      comments: 670,
      shares: 340,
      hook_text: "Your personal brand is your retirement plan",
      caption_text: "Why building a personal brand beats a 401k",
      breakout_score: 7.5,
      content_format: "talking_head",
    }),
    display_order: 4,
  },
  {
    id: "bs5",
    daily_report_id: "dr1",
    content: makeContent({
      id: "sc15",
      creator_name: "Vanessa Lau",
      creator_id: "c14",
      platform: "instagram",
      post_url: "https://instagram.com/p/single5",
      view_count: 156000,
      likes: 12300,
      comments: 890,
      shares: 560,
      hook_text: "I deleted 200 posts and my engagement tripled",
      caption_text: "Sometimes less really is more — here's the data",
      breakout_score: 7.8,
      content_format: "carousel",
    }),
    display_order: 5,
  },
];

export const todayReport: DailyReport = {
  id: "dr1",
  report_date: today,
  report_title: "The AI Content Takeover",
  total_trends_count: 4,
  total_breakout_videos_count: 15,
  published_at: new Date().toISOString(),
  trends,
  breakout_singles: breakoutSingles,
};

export const pastReports: Omit<DailyReport, "trends" | "breakout_singles">[] = [
  {
    id: "dr1",
    report_date: today,
    report_title: "The AI Content Takeover",
    total_trends_count: 4,
    total_breakout_videos_count: 15,
    published_at: new Date().toISOString(),
  },
  {
    id: "dr2",
    report_date: yesterday,
    report_title: "The Storytelling Hook Revolution",
    total_trends_count: 3,
    total_breakout_videos_count: 12,
    published_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "dr3",
    report_date: twoDaysAgo,
    report_title: "Raw Authenticity Wins",
    total_trends_count: 5,
    total_breakout_videos_count: 18,
    published_at: new Date(Date.now() - 172800000).toISOString(),
  },
];

export function getReportByDate(date: string): DailyReport | null {
  if (date === today) return todayReport;
  // For past reports, return the same data structure with adjusted dates for demo
  const past = pastReports.find((r) => r.report_date === date);
  if (!past) return null;
  return {
    ...todayReport,
    ...past,
    trends: todayReport.trends.map((t) => ({ ...t, daily_report_id: past.id })),
    breakout_singles: todayReport.breakout_singles.map((b) => ({ ...b, daily_report_id: past.id })),
  };
}
